table cleaned_data
	lineageTag: 4180f0f8-3e2a-47a2-8764-6403d8e7e191

	column posts
		dataType: string
		lineageTag: 32bbb006-f9cf-4ee4-9b1c-23c89e4554bc
		summarizeBy: none
		sourceColumn: posts

		annotation SummarizationSetBy = Automatic

	column cleaned_posts
		dataType: string
		lineageTag: 277c29d6-319a-40a1-8de1-49ff499df4d3
		summarizeBy: none
		sourceColumn: cleaned_posts

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 54e08b75-c9f6-42ec-8265-6e09047e14cc
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column personality_type
		dataType: string
		lineageTag: 8c34c4a9-9dcd-44b2-ab62-e5326cc615cd
		summarizeBy: none
		sourceColumn: personality_type

		annotation SummarizationSetBy = Automatic

	column word_count = LEN('cleaned_data'[cleaned_posts]) - LEN(SUBSTITUTE('cleaned_data'[cleaned_posts], " ", "")) + 1
		formatString: 0
		lineageTag: 978854da-347d-4630-a368-1da53541da60
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition cleaned_data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Admin\Downloads\DS project (second year) files\DS project (second year) files\cleaned_data.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "posts"}, {"Column2", "cleaned_posts"}, {"Column3", "type"}, {"Column4", "personality_type"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([personality_type] <> "personality_type"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

