table 'Model results (2)'
	lineageTag: 865a10cf-d0c6-4d40-a466-5d98c3bcd761

	column Metric
		dataType: string
		lineageTag: 2def8036-51a2-41af-be1e-3a89c9edab17
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column Precision
		dataType: decimal
		lineageTag: aab63bbc-a577-427b-a9ce-e78563bf14d9
		summarizeBy: sum
		sourceColumn: Precision

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Recall
		dataType: decimal
		lineageTag: 4e4bbe86-da6d-43ea-9b0d-8b1fc5b04098
		summarizeBy: sum
		sourceColumn: Recall

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F1-Score
		dataType: decimal
		lineageTag: 1955d3eb-fe34-415e-837d-0397e11db130
		summarizeBy: sum
		sourceColumn: F1-Score

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Model results (2)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("VYzLCoAgEEV/JWYtoWmOfou4EBNrEYH0oL+PnIhaHe7cM9c54MCAtwaxEo2lLAV45kDUpBRdNSerF7q2IcathHjS6yN9eUtziGVpwp5pQkuiNUSU1TrSlMc1Da+IRv7ndAfeXw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, Precision = _t, Recall = _t, #"F1-Score" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Precision", type text}, {"Recall", type text}, {"F1-Score", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

